Create help functionality
teamtaverna/slack_integration pull request #11
Opened 2017-03-28 17:39 UTC by kosyfrances

#8 

Create help functionality
Write tests

2017-03-29 11:51 UTC, kola-er requested changes
@andela-aomondi: Good job on the mock.

2017-03-29 11:51 UTC, kola-er commented on tests/faker.py
> +    def rtm_send_message(self, channel, message, attachments=None):
The parameter `attachments` is never used. What's its purpose?

2017-03-29 11:51 UTC, kola-er commented on tests/faker.py
> +    }
If I understood the purpose of this function, it is used to retrieve any kind of credential. So we might add another credential to the dict later. I think making it a dict is sufficient instead of function.

```
fake_creds = {
    'FAKE_CHANNEL': 'C12942JF92'
}
```

Does making it a function has some benefit?

2017-03-29 11:54 UTC, kosyfrances commented on tests/faker.py
> +    }
Some other tests might need to use more credentials, and I was worried about having a global variable, hence my reason for making it a function.

2017-03-29 11:58 UTC, kosyfrances commented on tests/faker.py
> +    def rtm_send_message(self, channel, message, attachments=None):
it's a param needed for rtm_send_message function. We got it from the tests in the library itself. The slackbot has an attachment functionality. if there is no attachment given to the slackbot, then it defaults to None.

2017-03-29 12:01 UTC, kola-er commented on tests/faker.py
> +    }
I don't think making it global prevents it from being used anywhere in others test cases. I believe it more or less a constant - so i don't expect its state to be changed anywhere  it's used.

2017-03-29 12:05 UTC, kosyfrances commented on tests/faker.py
> +    }
noted

2017-03-29 12:08 UTC, kola-er commented on tests/faker.py
> +    def rtm_send_message(self, channel, message, attachments=None):
Got it. But don't forget that this is a mock and the library has no idea of what goes on here. The library uses it even if it default to None, but our mock doesn't use it at all.

2017-03-29 12:09 UTC, kosyfrances commented on tests/faker.py
> +    def rtm_send_message(self, channel, message, attachments=None):
noted. I will update that.

2017-03-29 16:01 UTC, kosyfrances commented
@kola-er code has been updated to reflect your requested changes.

2017-03-29 17:55 UTC, kola-er approved these changes
Looks good!

2017-03-29 17:55 UTC, kola-er commented on tests/faker.py
> +FAKE_CHANNEL = 'C12942JF92'
I actually meant holding all the credentials in a dict:

```
fake_creds = {
    'FAKE_CHANNEL': 'C12942JF92',
}
```

All is good though.

2017-03-30 08:09 UTC, kosyfrances commented on tests/faker.py
> +FAKE_CHANNEL = 'C12942JF92'
We can make it a dict when we need to add more creds then.

2017-03-30 08:52 UTC, andela-cobiora commented on tests/faker.py
> +FAKE_CHANNEL = 'C12942JF92'
If we did that, wouldn't we have to remember all the places we used the`FAKE_CHANNEL` and then change those as well? I think we should go with @kola-er suggestion and avoid that technical debt.

2017-03-30 09:02 UTC, nbyodai requested changes

2017-03-30 09:02 UTC, andela-cobiora commented on common/utils.py
> +        loader=jinja2.FileSystemLoader(path)
nitpick: Would the value for `path` ever be different ? If not, might be cleaner to just pass `templates` into the `FileSystemLoader` function

2017-03-30 09:09 UTC, andela-snwuguru commented on common/utils.py
> +        loader=jinja2.FileSystemLoader(path)
We might need nested folders in the template in the future, I suggest we pass the `path` as a parameter with  `templates` as the default value.
```
def render(filename, path='templates', contex={}):
   pass
```

2017-04-03 07:35 UTC, kosyfrances commented
@andela-cobiora @andela-snwuguru changes updated. Please review.

2017-04-03 07:43 UTC, nbyodai approved these changes

2017-04-03 11:12 UTC, merged