create time service
teamtaverna/slack_integration pull request #9
Opened 2017-03-18 10:42 UTC by kosyfrances

#7

2017-03-18 10:59 UTC, kola-er approved these changes
Looks good.

2017-03-20 08:36 UTC, sundayguru approved these changes
Looks good

2017-03-20 08:47 UTC, nbyodai requested changes

2017-03-20 08:47 UTC, andela-cobiora commented on common/utils.py
> +        return date.today() + timedelta(days=1)
Although this looks good, I'm not sure it covers the use case very well. The idea behind the TimeService is this 
if a user puts in `tomorrow`, `yesterday`, `today`, `next tomorrow` we should have a way to parse that information and return the date object for our graphql to use as query filter.

If you look at your implementation, the only difference is the value being passed into `timedelta`. it also takes in a negative number so for where you've got
`date.today() - timedelta(days=1)` is the same as 
`date.today() + timedelta(days=-1)`
and today is same as `date.today() + timedelta(days=0)`

We only need one function
```
def get_date(day_arg=0):
  # Do the magic of conversion inside here
  return date.today() + timedelta(days=day_arg)
```
The TimeService would still need a good way to parse possible entries in order to get the `day_arg`
These are possible different types 
**number_days_type** e.g `5 days, 2 days`
**today_tomorrow_yesterday_type** e.g `today, tomorrow,  `
**day_name_type** e.g `monday , tuesday`
**next_type** e.g `next week, next monday, next wednesday`
**date_type** e.g `12th of March`

We would need another function to accurately determine the `day _arg` based on the type.

2017-03-20 08:48 UTC, andela-cobiora commented on common/utils.py
> +        return date.today() + timedelta(days=1)
Do reach out if anything is unclear

2017-03-27 07:53 UTC, kosyfrances commented
@andela-cobiora @kola-er @andela-snwuguru please review above changes.

2017-03-27 08:18 UTC, nbyodai requested changes

2017-03-27 08:18 UTC, andela-cobiora commented on common/utils.py
> +                return 0 - (current_weekday_num - day_index)
if you use `day_index - current_weekday_num` here, then you wouldn't have to use the `0 -` part

2017-03-27 08:18 UTC, andela-cobiora commented on common/utils.py
> +                return (day_index - current_weekday_num)
Is the use of `()` here necessary?

2017-03-27 08:18 UTC, andela-cobiora commented on tests/test_utils.py
> +class GetDateTest(unittest.TestCase):
👍

2017-03-27 08:18 UTC, kosyfrances commented on common/utils.py
> +                return (day_index - current_weekday_num)
Just for clean code consistency sake.

2017-03-27 08:29 UTC, kosyfrances commented
@andela-cobiora changes updated

2017-03-27 09:00 UTC, nbyodai approved these changes

2017-03-27 09:05 UTC, merged